steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - 'gcloud'
      - 'functions'
      - 'deploy'
      - 'petrol-scraper-func'
      - '--gen2'
      - '--runtime=python311'
      - '--region=europe-west1'
      - '--source=./landing'
      - '--entry-point=run_pipeline'
      - '--trigger-http'
      - '--no-allow-unauthenticated'
options:
  logging: CLOUD_LOGGING_ONLY