name: Deploy Petrol Scraper to GCP

on:
  push:
    branches:
      - main  # Change to 'master' if that is your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Function Gen 2
        run: |
          gcloud functions deploy petrol-scraper-func \
            --gen2 \
            --runtime=python314 \
            --region=europe-west1 \
            --source=. \
            --entry-point=main \
            --trigger-http \
            --allow-unauthenticated \
            --project=petrol-webscrape \
            --timeout=1800s